Repository acm-ucr/hiss-website, pull requests merged in 2023-11, with the labels that each got.

#30 aldrieBarcena/boardsComponent
  src/app/page.js
  src/components/board/Card.jsx
  src/components/board/Cards.jsx
Labels: board, ready to review

#29 footer
  src/components/Footer.jsx
Labels: ready to review

#28 made landing
  src/components/about/Landing.jsx
Labels: ready to review

#44 Aldrie barcena/increase space between board
  src/app/board/page.js
Labels: ready to review

#43 Title on smaller screens
  src/components/Title.jsx
Labels: ready to review

#46 Reponsive Join Us
  src/components/about/Card.jsx
  src/components/about/Cards.jsx
Labels: ready to review

#42 semi-fixed bar
  src/components/Navigation.jsx
Labels: in progress

#20 Progress for Event.jsx
  src/components/Event.jsx
Labels: ready to review

#54 Color on Hover Join Cards
  src/components/about/Card.jsx
Labels: ready to review

#56 Hover Animation to Footer Icons
  src/components/Footer.jsx
Labels: ready to review, animate

#57 responsive landing on mobile
  src/components/about/Landing.jsx
Labels: address comments

#31 Created About Us Component
  src/components/about/HISS.jsx
Labels: about, address comments

#60 About Us Component
  src/components/about/HISS.jsx
Labels: about, ready to review

#61 Vidhi/button
  src/components/Events.jsx
  src/components/about/Button.jsx
  src/components/about/Landing.jsx
Labels: about

#59 increased title size
  src/components/Title.jsx
Labels: ready to review

#71 fixed join position
  src/components/Navigation.jsx
Labels: ready to review

#70 Hover Board Icon Animate
  src/components/board/Card.jsx
Labels: animate

#73 position button on landing
  src/app/events/page.js
  src/app/page.js
  src/components/Events.jsx
  src/components/about/Landing.jsx
Labels: help wanted

#78 fixed board overflow
  src/components/board/Card.jsx
Labels: ready to review

#79 Made event card mobile responsive
  src/components/Event.jsx
Labels: ready to review

#80 Responsive About Us
  src/components/about/HiSS.jsx
Labels: help wanted
