Repository acm-ucr/hiss-website, pull requests merged in 2023-12, with the labels that each got.

#86 Vidhi - button space
  src/components/Events.jsx
Labels: events

#103 fixed nabar height
  src/components/Navigation.jsx
Labels: ready to review

#107 Added LinkedIn to Footer
  src/components/Footer.jsx
Labels: about, ready to review

#110 added circles
  src/app/page.js
  src/components/about/CircleHiSS.jsx
Labels: ready to review

#109 Animated Join Cards
  src/components/about/Cards.jsx
Labels: ready to review, animate

#45 current calendar
  package-lock.json
  package.json
  src/components/calendar/Calendar.jsx
  src/components/calendar/CustomEvents.jsx
  src/components/calendar/CustomHeader.jsx
  src/components/calendar/CustomToolbar.jsx
  src/components/calendar/Modal.jsx
  src/components/calendar/index.css
  tailwind.config.js
Labels: ready to review

#114 added 10 week timeframe
  src/components/calendar/Calendar.jsx
Labels: ready to review
